# Makefile: A standard Makefile for main.c

#CPPFLAGS = -I/usr/include/libxml2
LDLIBS = -ldl

all  : maple_explorer
run:
	LD_LIBRARY_PATH=/opt/maple2021/bin.X86_64_LINUX ./maple_explorer
clean:
	/bin/rm -rf maple_explorer maple_explorer.o
# END OF FILE
