# Makefile: A standard Makefile for main.cpp

all  : exemplo01 exemplo02

exemplo01: exemplo01.o
	gcc -o $@ $^

exemplo02: exemplo02.o
	g++ -o $@ $^

clean:
	/bin/rm -rf  exemplo01 exemplo01.o exemplo02 exemplo02.o dados.bin
# END OF FILE
