# Makefile: A standard Makefile for spinapp.cpp

CPPFLAGS=-g -Wall -Wno-parentheses
LDLIBS = `wx-config --cxxflags --libs`
#LDFLAGS = -L./

all  : spinapp
clean:
	/bin/rm -rf spinapp spinapp.o
# END OF FILE
