# Makefile: A standard Makefile for main.c
#
CXX      = /home/linuxbrew/.linuxbrew/bin/g++-16
#CPPFLAGS =
CXXFLAGS = -Wall -Wno-parentheses -std=c++20
#LDFLAGS  =
#LDLIBS   =

all: main

run: main
	./main

clean:
	$(RM) main main.o

.PHONY: all run clean
