# Makefile: A standard Makefile for main.c

#CPPFLAGS = -I/usr/include/libxml2
#LDLIBS = -lm

all  : meucodigo.oct

meucodigo.oct:meucodigo.cpp
	mkoctfile -v meucodigo.cpp
clean:
	/bin/rm -rf meucodigo.oct 
# END OF FILE
